import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const supabase = readFileSync(new URL("../src/lib/supabase.ts", import.meta.url), "utf8")
assert.match(supabase, /ubuntu\.from\(["']ua_users["']\)\.insert/, "signup writes Ubuntu ua_users only")
assert.match(supabase, /pending_aureus_provision:\s*true/, "new Ubuntu users are queued for Aureus identity, not written live")
assert.match(supabase, /\/api\/ua-login/, "Aureus users sign in through official Aureus initiate-login, not Supabase Auth")
assert.doesNotMatch(supabase, /aureusRead\.auth\.signInWithPassword/, "client no longer uses Aureus Supabase Auth password grant")
assert.doesNotMatch(supabase, /user_projects/, "no Aureus user_projects writes")
assert.match(supabase, /readAureusShareholderByEmail/, "Aureus shareholder read helper exists")

const readonly = readFileSync(new URL("../src/lib/aureusReadOnly.ts", import.meta.url), "utf8")
assert.match(readonly, /Aureus live database is read-only/, "read-only guard message present")
assert.match(readonly, /insert/, "write methods blocked")
assert.match(readonly, /AUREUS_AUTH_BLOCKED/, "only explicit Aureus auth writes are blocked")
assert.match(readonly, /signUp/, "Aureus signup remains blocked")
assert.match(readonly, /value\.bind\(authTarget\)/, "Aureus sign-in internals stay callable")

const ubuntu = readFileSync(new URL("../src/lib/ubuntuDb.ts", import.meta.url), "utf8")
assert.match(ubuntu, /fgubaqoftdeefcakejwu/, "Ubuntu client refuses Aureus project ref")
assert.match(ubuntu, /assertUbuntuWriteTarget/, "write target assertion exported")

const env = readFileSync(new URL("../.env.example", import.meta.url), "utf8")
assert.match(env, /VITE_UBUNTU_SUPABASE_URL/, "Ubuntu write env documented")
assert.match(env, /VITE_AUREUS_SUPABASE_URL/, "Aureus read env documented")
assert.match(env, /UA_COMMERCE_CONFIRM_SECRET/, "confirm/BLP close secret is documented")
assert.doesNotMatch(env, /VITE_SUPABASE_URL=https:\/\/fgubaqoftdeefcakejwu/, "old single Aureus write URL removed")

const runner = readFileSync(new URL("../deploy/run-migrations.js", import.meta.url), "utf8")
assert.match(runner, /will not connect to Aureus production/, "migration runner refuses Aureus")
assert.match(runner, /ubuntu-only/, "runner applies Ubuntu-only SQL")
assert.doesNotMatch(runner, /001_create_projects_system/, "old Aureus project-table migrations are not run")

const dashboard = readFileSync(new URL("../src/routes/dashboard/index.tsx", import.meta.url), "utf8")
assert.match(dashboard, /current\.profile/, "dashboard uses server-loaded Aureus profile")
assert.doesNotMatch(dashboard, /loadAureusMemberByAuthId/, "dashboard does not query Aureus from the browser")
assert.doesNotMatch(dashboard, /project_id/, "dashboard does not query Aureus project_id")

const uaLogin = readFileSync(new URL("../src/routes/api/ua-login.ts", import.meta.url), "utf8")
assert.match(uaLogin, /initiate-login/, "Ubuntu login proxies official Aureus bcrypt login")
assert.doesNotMatch(uaLogin, /signInWithPassword/, "login proxy does not use Supabase Auth password grant")
assert.doesNotMatch(uaLogin, /createClient/, "login admin lookup uses Aureus REST headers, not supabase-js JWT Bearer")

const uaMe = readFileSync(new URL("../src/routes/api/ua-me.ts", import.meta.url), "utf8")
assert.match(uaMe, /aureusRestMaybeSingle/, "ua-me loads Aureus profile through REST apikey headers")
assert.doesNotMatch(uaMe, /createClient/, "ua-me does not use supabase-js against sb_secret keys")
assert.match(uaMe, /warning/, "ua-me keeps the session usable if Aureus profile fetch fails")

const aureusAdmin = readFileSync(new URL("../src/lib/aureusAdminRest.server.ts", import.meta.url), "utf8")
assert.match(aureusAdmin, /charCodeAt/, "server rejects masked non-ASCII Aureus secrets")
assert.match(aureusAdmin, /apikey/, "Aureus REST sends apikey header")

const affiliate = readFileSync(new URL("../src/routes/affiliate/index.tsx", import.meta.url), "utf8")
assert.match(affiliate, /ua_users/, "affiliate reads Ubuntu users")
assert.doesNotMatch(affiliate, /project_id/, "affiliate does not query Aureus project_id")
assert.match(affiliate, /SSA/, "affiliate shows corporate ranks")
assert.doesNotMatch(affiliate, /10% USDT/, "legacy 10% USDT copy removed")
assert.doesNotMatch(affiliate, /Daily Pool/, "legacy daily pool copy removed")

const schema = readFileSync(new URL("../supabase/ubuntu-only/0003_ua_gap_cover_core.sql", import.meta.url), "utf8")
assert.match(schema, /NEVER run this on Aureus production/, "0003 refuses Aureus")
assert.match(schema, /ua_commission_transactions/, "commission ledger exists")
assert.match(schema, /nft_marketplace_enabled/, "NFT flag exists and defaults off in settings seed")

const schema4 = readFileSync(new URL("../supabase/ubuntu-only/0004_ua_cards_fractions.sql", import.meta.url), "utf8")
assert.match(schema4, /NEVER run this on Aureus production/, "0004 refuses Aureus")
assert.match(schema4, /ua_card_orders/, "card orders table exists")
assert.match(schema4, /ua_fraction_transactions/, "fraction transactions table exists")

const invest = readFileSync(new URL("../src/routes/dashboard/invest.tsx", import.meta.url), "utf8")
assert.match(invest, /checkout is not open/, "commerce checkout is not open")
assert.doesNotMatch(invest, /aureusSharePrice:\s*"100.00"/, "invest quote does not send a client phase price")
assert.doesNotMatch(invest, /\/api\/invest\/purchase/, "no fake invest purchase path")
assert.doesNotMatch(invest, /\/api\/admin\/commerce\/confirm-payment/, "public invest page cannot confirm payment")
assert.doesNotMatch(invest, /\/api\/cards\/order/, "public invest page cannot create card orders")
assert.doesNotMatch(invest, /\/api\/fractions\/order/, "public invest page cannot create fraction orders")
assert.doesNotMatch(invest, /\/api\/admin\/commerce\/create-order/, "public invest page cannot create admin orders")

const publicCardOrder = readFileSync(new URL("../src/routes/api/cards/order.ts", import.meta.url), "utf8")
assert.match(publicCardOrder, /Public checkout is not open/, "public card order path is closed")
assert.match(publicCardOrder, /status: 403/, "public card order stays 403")
assert.doesNotMatch(publicCardOrder, /ua_card_orders/, "public card order does not insert Ubuntu rows")

const publicFractionOrder = readFileSync(new URL("../src/routes/api/fractions/order.ts", import.meta.url), "utf8")
assert.match(publicFractionOrder, /Public checkout is not open/, "public fraction order path is closed")
assert.match(publicFractionOrder, /status: 403/, "public fraction order stays 403")
assert.doesNotMatch(publicFractionOrder, /ua_fraction_transactions/, "public fraction order does not insert Ubuntu rows")

const createOrder = readFileSync(new URL("../src/routes/api/admin/commerce/create-order.ts", import.meta.url), "utf8")
assert.match(createOrder, /UA_COMMERCE_CONFIRM_SECRET/, "admin order create is secret-gated")
assert.match(createOrder, /Client-supplied rank chains are rejected/, "admin order create rejects client rank chains")
assert.match(createOrder, /persistPendingCardOrder/, "admin create inserts ua_card_orders")
assert.match(createOrder, /persistPendingFractionOrder/, "admin create inserts ua_fraction_transactions")
assert.match(createOrder, /PENDING_PAYMENT|createPendingCardOrder/, "admin create starts as pending")
assert.match(createOrder, /loadActiveAureusPhase/, "admin fraction create reads live Ubuntu phase")
assert.match(createOrder, /loadUnderlyingInventory/, "admin fraction create reads live Ubuntu remaining")
assert.match(createOrder, /taken from Ubuntu inventory/, "admin fraction create rejects client remaining")
assert.match(createOrder, /taken from Ubuntu ua_aureus_phases/, "admin fraction create rejects client phase price")
assert.match(createOrder, /checkoutEnabled: false/, "admin create keeps checkout closed")
assert.match(createOrder, /loadUbuntuUser/, "admin create requires an existing Ubuntu ua_users.id")
assert.match(createOrder, /Ubuntu user not found/, "missing Ubuntu user is refused")
assert.match(createOrder, /not active/, "inactive Ubuntu user is refused")
assert.doesNotMatch(createOrder, /body\.aureusSharePrice \|\| "100\.00"/, "admin create does not default a client phase price")
assert.doesNotMatch(createOrder, /fgubaqoftdeefcakejwu/, "admin create never targets Aureus")

const confirmPay = readFileSync(new URL("../src/routes/api/admin/commerce/confirm-payment.ts", import.meta.url), "utf8")
assert.match(confirmPay, /UA_COMMERCE_CONFIRM_SECRET/, "payment confirm is secret-gated")
assert.match(confirmPay, /Client-supplied rank chains are rejected/, "confirm API rejects client rank chains")
assert.match(confirmPay, /processGapCover|confirmCommercePayment/, "confirm uses the shared Gap Cover path")
assert.match(confirmPay, /persistConfirmVolume/, "confirm credits monthly QV and open BLP period")
assert.match(confirmPay, /Pending order not found/, "confirm requires a real persisted pending row")
assert.match(confirmPay, /orderFromCardRow|orderFromFractionRow/, "confirm rebuilds from the Ubuntu row, not client product fields")
assert.match(confirmPay, /persistFractionInventory/, "fraction confirm decrements Ubuntu remaining inventory")
assert.match(confirmPay, /fulfilment_status/, "card confirm starts fulfilment after PAID")
assert.match(confirmPay, /PROCESSING/, "card confirm fulfilment starts at PROCESSING")
assert.match(confirmPay, /loadUbuntuUser/, "confirm rechecks Ubuntu ua_users before settle")
assert.match(confirmPay, /not active/, "inactive Ubuntu user cannot be confirmed")
assert.doesNotMatch(confirmPay, /\/dashboard\/invest/, "confirm API is not the public invest page")

const schema7 = readFileSync(new URL("../supabase/ubuntu-only/0007_ua_fraction_inventory.sql", import.meta.url), "utf8")
assert.match(schema7, /NEVER run this on Aureus production/, "0007 refuses Aureus")
assert.match(schema7, /ua_liability_source_type/, "fraction sale ledger is unique per order")

const persistInventory = readFileSync(new URL("../src/lib/persistInventory.server.ts", import.meta.url), "utf8")
assert.match(persistInventory, /ua_underlying_inventory/, "inventory persist writes Ubuntu remaining")
assert.match(persistInventory, /FRACTION_SALE/, "inventory consume is ledgered")
assert.match(persistInventory, /exceeds remaining underlying/, "sold-through confirm is refused")
assert.match(persistInventory, /persistFractionReserve/, "pending fraction can reserve Ubuntu inventory")
assert.match(persistInventory, /FRACTION_RESERVE/, "reserve is ledgered separately from sale")
assert.match(persistInventory, /convertReserveToSale/, "confirm converts a reserve without decrementing remaining again")
assert.doesNotMatch(persistInventory, /fgubaqoftdeefcakejwu/, "inventory persist never targets Aureus")

const fractionQuote = readFileSync(new URL("../src/routes/api/fractions/quote.ts", import.meta.url), "utf8")
assert.match(fractionQuote, /loadUnderlyingInventory/, "fraction quote reads live Ubuntu remaining")
assert.match(fractionQuote, /loadActiveAureusPhase/, "fraction quote reads live Ubuntu phase price")
assert.match(fractionQuote, /taken from Ubuntu inventory/, "fraction quote rejects client remaining")
assert.match(fractionQuote, /taken from Ubuntu ua_aureus_phases/, "fraction quote rejects client phase price")
assert.match(fractionQuote, /checkoutEnabled: false/, "fraction quote keeps checkout closed")
assert.doesNotMatch(fractionQuote, /\.insert\(|\.update\(|\.delete\(/, "fraction quote does not write inventory")

const fractionAvail = readFileSync(new URL("../src/routes/api/fractions/availability.ts", import.meta.url), "utf8")
assert.match(fractionAvail, /loadUnderlyingInventory/, "fraction availability reads live Ubuntu remaining")
assert.match(fractionAvail, /loadActiveAureusPhase/, "fraction availability reads live Ubuntu phase price")
assert.match(fractionAvail, /taken from Ubuntu inventory/, "fraction availability rejects client remaining")
assert.match(fractionAvail, /taken from Ubuntu ua_aureus_phases/, "fraction availability rejects client phase price")
assert.match(fractionAvail, /checkoutEnabled: false/, "fraction availability keeps checkout closed")
assert.doesNotMatch(fractionAvail, /\.insert\(|\.update\(|\.delete\(/, "fraction availability does not write inventory")

const currentPhase = readFileSync(new URL("../src/routes/api/aureus/current-phase.ts", import.meta.url), "utf8")
assert.match(currentPhase, /loadActiveAureusPhase/, "current-phase reads live Ubuntu ua_aureus_phases")
assert.match(currentPhase, /loadUnderlyingInventory/, "current-phase includes live remaining")
assert.match(currentPhase, /checkoutEnabled: false/, "current-phase keeps checkout closed")
assert.doesNotMatch(currentPhase, /\.insert\(|\.update\(|\.delete\(/, "current-phase does not write Ubuntu")
assert.doesNotMatch(currentPhase, /DEFAULT_PHASE/, "current-phase no longer hardcodes DEFAULT_PHASE")

const ubuntuServerAfter = readFileSync(new URL("../src/lib/ubuntuServer.server.ts", import.meta.url), "utf8")
assert.match(ubuntuServerAfter, /loadUnderlyingInventory/, "Ubuntu inventory loader exists")
assert.match(ubuntuServerAfter, /ua_underlying_inventory/, "inventory loader reads Ubuntu remaining")
assert.match(ubuntuServerAfter, /loadActiveAureusPhase/, "Ubuntu active phase loader exists")
assert.match(ubuntuServerAfter, /ua_aureus_phases/, "phase loader reads Ubuntu ua_aureus_phases")
assert.match(ubuntuServerAfter, /loadUbuntuUser/, "Ubuntu user loader exists")
assert.match(ubuntuServerAfter, /from\("ua_users"\)/, "user loader reads Ubuntu ua_users")
assert.match(ubuntuServerAfter, /is_active/, "user loader checks Ubuntu is_active")
assert.match(ubuntuServerAfter, /Ubuntu user is not active/, "inactive users are refused")

const processApi = readFileSync(new URL("../src/routes/api/commissions/process.ts", import.meta.url), "utf8")
assert.match(processApi, /processGapCover/, "shared Gap Cover engine is the only processor")
assert.match(processApi, /getUbuntuServerClient/, "commission writes use the Ubuntu server client")
assert.match(processApi, /loadUbuntuUser/, "commission process rechecks Ubuntu ua_users")
assert.match(processApi, /not active/, "inactive seller cannot process commissions")
assert.doesNotMatch(processApi, /fgubaqoftdeefcakejwu/, "commission process never targets Aureus")

const gapEngine = readFileSync(new URL("../src/lib/gapCover.mjs", import.meta.url), "utf8")
assert.match(gapEngine, /isActive === false/, "Gap Cover refuses payout to inactive recipients")
assert.match(gapEngine, /absorbedUnclaimed/, "inactive Gap stays unclaimed with Ubuntu Afrique")

const schema5 = readFileSync(new URL("../supabase/ubuntu-only/0005_ua_blp.sql", import.meta.url), "utf8")
assert.match(schema5, /NEVER run this on Aureus production/, "0005 refuses Aureus")
assert.match(schema5, /ua_blp_periods/, "BLP period table exists")
assert.match(schema5, /ua_blp_transactions/, "BLP transaction table exists")

const blpClose = readFileSync(new URL("../src/routes/api/admin/blp/close-period.ts", import.meta.url), "utf8")
assert.match(blpClose, /UA_COMMERCE_CONFIRM_SECRET/, "BLP close is secret-gated")
assert.match(blpClose, /Client-supplied rank chains are rejected/, "BLP close rejects client rank chains")
assert.match(blpClose, /distributeBlpPeriod/, "BLP close uses the shared BLP engine")
assert.match(blpClose, /loadBlpMembers/, "BLP members load from Ubuntu ranks and monthly volume")
assert.match(blpClose, /isActive === true/, "BLP close pays only active Ubuntu members")
assert.match(blpClose, /taken from the open Ubuntu BLP period/, "close rejects client-supplied BLP sales")
assert.match(blpClose, /commissionable_sales/, "close distributes from stored period sales")
assert.match(blpClose, /monthlyVolumeReset/, "close reports monthly team QV reset")

const schema6 = readFileSync(new URL("../supabase/ubuntu-only/0006_ua_blp_contributions.sql", import.meta.url), "utf8")
assert.match(schema6, /NEVER run this on Aureus production/, "0006 refuses Aureus")
assert.match(schema6, /ua_blp_contributions/, "BLP contribution ledger exists")

const persistPending = readFileSync(new URL("../src/lib/persistPending.server.ts", import.meta.url), "utf8")
assert.match(persistPending, /ua_card_orders/, "pending persist writes Ubuntu card orders")
assert.match(persistPending, /ua_fraction_transactions/, "pending persist writes Ubuntu fraction transactions")
assert.match(persistPending, /Ubuntu user not found/, "pending persist refuses a missing Ubuntu user id")
assert.match(persistPending, /price_version_id/, "pending card persist passes price_version_id")
assert.match(persistPending, /price_version(?!_id)/, "pending fraction persist passes price_version")
assert.doesNotMatch(persistPending, /fgubaqoftdeefcakejwu/, "pending persist never targets Aureus")

const persistPricing = readFileSync(new URL("../src/lib/persistPricing.server.ts", import.meta.url), "utf8")
assert.match(persistPricing, /export async function loadCurrentPriceVersion/, "current price version loader exists")
assert.match(persistPricing, /ua_product_price_versions/, "price version loader reads Ubuntu price versions")
assert.match(persistPricing, /end_date/, "price version loader keeps the open version")
assert.match(persistPricing, /effective_date/, "price version loader orders by effective date")
assert.match(persistPricing, /ua_products/, "missing price version is snapshotted from ua_products")
assert.doesNotMatch(persistPricing, /fgubaqoftdeefcakejwu/, "price version loader never targets Aureus")

const commerceOrders = readFileSync(new URL("../src/lib/commerceOrders.mjs", import.meta.url), "utf8")
assert.match(commerceOrders, /price_version_id/, "pending card insert stores price_version_id")
assert.match(commerceOrders, /price_version(?!_id)/, "pending fraction insert stores price_version")
assert.match(commerceOrders, /taken from Ubuntu price versions, not the client/, "order create rejects a client price")
assert.match(commerceOrders, /assertSnapshotCharge/, "confirm path asserts snapshot charge")
assert.match(commerceOrders, /price-version snapshot/, "charged amount requires Ubuntu price-version snapshot")
assert.match(commerceOrders, /commissionableValue = order\.total/, "snapshot confirm charges order.total not catalog")
assert.match(confirmPay, /confirmCommercePayment/, "confirm-payment settles via shared commerce confirm")

const recordPay = readFileSync(new URL("../src/routes/api/admin/commerce/record-payment.ts", import.meta.url), "utf8")
assert.match(recordPay, /UA_COMMERCE_CONFIRM_SECRET/, "staging payment record is secret-gated")
assert.match(recordPay, /persistPaymentEvent/, "staging payment writes ua_payment_events")
assert.match(recordPay, /checkoutEnabled: false/, "staging payment keeps checkout closed")
assert.doesNotMatch(recordPay, /confirmCommercePayment/, "record-payment does not settle Gap")
assert.doesNotMatch(recordPay, /fgubaqoftdeefcakejwu/, "record-payment never targets Aureus")

const adminCardOrders = readFileSync(new URL("../src/routes/api/admin/cards/orders.ts", import.meta.url), "utf8")
assert.match(adminCardOrders, /UA_COMMERCE_CONFIRM_SECRET/, "admin card list is secret-gated")
assert.match(adminCardOrders, /ua_card_orders/, "admin card list reads Ubuntu card orders")
assert.match(adminCardOrders, /checkoutEnabled: false/, "admin card list keeps checkout closed")

const adminFractionOrders = readFileSync(new URL("../src/routes/api/admin/fractions/orders.ts", import.meta.url), "utf8")
assert.match(adminFractionOrders, /UA_COMMERCE_CONFIRM_SECRET/, "admin fraction list is secret-gated")
assert.match(adminFractionOrders, /ua_fraction_transactions/, "admin fraction list reads Ubuntu fraction rows")
assert.match(adminFractionOrders, /checkoutEnabled: false/, "admin fraction list keeps checkout closed")

const schema12 = readFileSync(new URL("../supabase/ubuntu-only/0012_ua_payment_events.sql", import.meta.url), "utf8")
assert.match(schema12, /NEVER run this on Aureus production|NEVER run on Aureus/, "0012 refuses Aureus")
assert.match(schema12, /ua_payment_events/, "0012 adds Ubuntu payment events")

assert.match(createOrder, /loadCurrentPriceVersion/, "admin create loads the Ubuntu price version")
assert.match(createOrder, /applyPriceVersionSnapshot/, "admin create copies unit and total from the price version")
assert.match(createOrder, /persistFractionReserve/, "admin fraction create reserves Ubuntu inventory")
assert.match(createOrder, /taken from Ubuntu price versions, not the client/, "admin create rejects client priceVersion")
assert.match(createOrder, /body\[key\]/, "admin create inspects client priceVersion fields")
assert.doesNotMatch(createOrder, /unit_price:\s*body/, "admin create does not persist a client unit price")

const schema8 = readFileSync(new URL("../supabase/ubuntu-only/0008_ua_price_version_seeds.sql", import.meta.url), "utf8")
assert.match(schema8, /NEVER run on Aureus fgubaqoftdeefcakejwu/, "0008 refuses Aureus")
assert.match(schema8, /INSERT INTO public\.ua_product_price_versions/, "0008 inserts price versions from ua_products")
assert.match(schema8, /end_date IS NULL/, "0008 inserts a version only when none is open")
assert.doesNotMatch(schema8, /CREATE TABLE/, "0008 does not recreate tables")

const schema9 = readFileSync(new URL("../supabase/ubuntu-only/0009_ua_card_fulfilment_status.sql", import.meta.url), "utf8")
assert.match(schema9, /NEVER run this on Aureus production/, "0009 refuses Aureus")
assert.match(schema9, /fulfilment_status/, "0009 adds card fulfilment_status")

const cardStatus = readFileSync(new URL("../src/routes/api/admin/cards/status.ts", import.meta.url), "utf8")
assert.match(cardStatus, /UA_COMMERCE_CONFIRM_SECRET/, "card fulfilment status is secret-gated")
assert.match(cardStatus, /advanceCardFulfilment/, "card status uses the shared fulfilment path")
assert.match(cardStatus, /Card fulfilment starts after PAID/, "fulfilment cannot start before PAID")
assert.match(cardStatus, /checkoutEnabled: false/, "card status keeps checkout closed")
assert.doesNotMatch(cardStatus, /fgubaqoftdeefcakejwu/, "card status never targets Aureus")

const schema10 = readFileSync(new URL("../supabase/ubuntu-only/0010_ua_transaction_reversals.sql", import.meta.url), "utf8")
assert.match(schema10, /NEVER run this on Aureus production/, "0010 refuses Aureus")
assert.match(schema10, /ua_transaction_reversals/, "0010 adds reversal records")
assert.match(schema10, /ua_reversal_source_type/, "refund reversal is unique per order")

const persistRefund = readFileSync(new URL("../src/lib/persistRefund.server.ts", import.meta.url), "utf8")
assert.match(persistRefund, /ua_transaction_reversals/, "refund persist writes reversal records")
assert.match(persistRefund, /entry_type: "REVERSAL"/, "refund persist posts wallet reversals")
assert.match(persistRefund, /commission_type: "REVERSAL"/, "refund persist posts commission reversals")
assert.doesNotMatch(persistRefund, /\.delete\(/, "refund persist does not delete original financial rows")
assert.doesNotMatch(persistRefund, /fgubaqoftdeefcakejwu/, "refund persist never targets Aureus")

const cardRefund = readFileSync(new URL("../src/routes/api/admin/cards/refund.ts", import.meta.url), "utf8")
assert.match(cardRefund, /UA_COMMERCE_CONFIRM_SECRET/, "card refund is secret-gated")
assert.match(cardRefund, /reverseCardOrder/, "card refund uses the shared reversal path")
assert.match(cardRefund, /Card refund requires fulfilment to exist/, "refund refuses before fulfilment")
assert.match(cardRefund, /checkoutEnabled: false/, "card refund keeps checkout closed")
assert.doesNotMatch(cardRefund, /fgubaqoftdeefcakejwu/, "card refund never targets Aureus")

const fractionRefund = readFileSync(new URL("../src/routes/api/admin/fractions/refund.ts", import.meta.url), "utf8")
assert.match(fractionRefund, /UA_COMMERCE_CONFIRM_SECRET/, "fraction refund is secret-gated")
assert.match(fractionRefund, /reverseFractionOrder/, "fraction refund uses the shared reversal path")
assert.match(fractionRefund, /checkoutEnabled: false/, "fraction refund keeps checkout closed")
assert.doesNotMatch(fractionRefund, /fgubaqoftdeefcakejwu/, "fraction refund never targets Aureus")

const persistInventoryAfter = readFileSync(new URL("../src/lib/persistInventory.server.ts", import.meta.url), "utf8")
assert.match(persistInventoryAfter, /persistFractionRefundRestore/, "fraction refund restore exists")
assert.match(persistInventoryAfter, /FRACTION_SALE_REVERSAL/, "sale reversal is ledgered")
assert.match(persistInventoryAfter, /FRACTION_RESERVE_RELEASE/, "reserve release is ledgered")

const persistRefundAfter = readFileSync(new URL("../src/lib/persistRefund.server.ts", import.meta.url), "utf8")
assert.match(persistRefundAfter, /persistFractionRefund/, "fraction refund persist exists")
assert.match(persistRefundAfter, /FRACTION_REFUND/, "fraction refund reversal type exists")

const liabilityEngine = readFileSync(new URL("../src/lib/liabilityEngine.mjs", import.meta.url), "utf8")
assert.match(liabilityEngine, /FRACTION_REMITTED/, "remitted is a distinct liability class")
assert.match(liabilityEngine, /outstanding/, "outstanding is original minus remitted")

const persistLiability = readFileSync(new URL("../src/lib/persistLiability.server.ts", import.meta.url), "utf8")
assert.match(persistLiability, /persistLiabilityRemitted/, "remit helper exists and is not an API")
assert.doesNotMatch(persistLiability, /fgubaqoftdeefcakejwu/, "liability persist never targets Aureus")

const schema11 = readFileSync(new URL("../supabase/ubuntu-only/0011_ua_liability_reserved_remitted.sql", import.meta.url), "utf8")
assert.match(schema11, /NEVER run this on Aureus production/, "0011 refuses Aureus")
assert.match(schema11, /RESERVED DOES NOT MEAN PAID/, "0011 documents reserved vs remitted")

const persistVolume = readFileSync(new URL("../src/lib/persistVolume.server.ts", import.meta.url), "utf8")
assert.match(persistVolume, /monthly_team_qv/, "confirm persist credits monthly team QV")
assert.match(persistVolume, /ua_blp_contributions/, "confirm persist accrues open BLP period")
assert.doesNotMatch(persistVolume, /fgubaqoftdeefcakejwu/, "volume persist never targets Aureus")

const persistBlp = readFileSync(new URL("../src/lib/persistBlp.server.ts", import.meta.url), "utf8")
assert.match(persistBlp, /entry_type: "BLP"/, "BLP posts to the Ubuntu wallet ledger")
assert.match(persistBlp, /monthly_team_qv: "0.00"/, "BLP close resets monthly team QV after payout")
assert.match(persistBlp, /monthlyVolumeReset/, "BLP close reports the monthly QV reset")
assert.doesNotMatch(persistBlp, /fgubaqoftdeefcakejwu/, "BLP persist never targets Aureus")
assert.ok(
  persistBlp.indexOf('monthly_team_qv: "0.00"') > persistBlp.indexOf("ua_blp_transactions"),
  "monthly QV reset happens after BLP payouts are written"
)
assert.ok(
  persistBlp.indexOf('status: "CLOSED"') > persistBlp.indexOf('monthly_team_qv: "0.00"'),
  "period is marked CLOSED only after monthly QV reset"
)

const ubuntuServer = readFileSync(new URL("../src/lib/ubuntuServer.server.ts", import.meta.url), "utf8")
assert.match(ubuntuServer, /Aureus production/, "commission API refuses Aureus writes")
assert.match(ubuntuServer, /loadBlpMembers/, "BLP member loader exists")
assert.match(ubuntuServer, /monthly_team_qv/, "BLP qualification uses monthly team QV")
assert.match(ubuntuServer, /loadBlpMembers[\s\S]*is_active/, "BLP loader reads Ubuntu ua_users.is_active")

const rankPromote = readFileSync(new URL("../src/routes/api/admin/ranks/promote.ts", import.meta.url), "utf8")
assert.match(rankPromote, /UA_COMMERCE_CONFIRM_SECRET/, "rank promote is secret-gated")
assert.match(rankPromote, /evaluateRankQualification/, "rank promote uses the shared qualification engine")
assert.match(rankPromote, /persistRankPromotion/, "rank promote persists Ubuntu ranks")
assert.match(rankPromote, /checkoutEnabled: false/, "rank promote keeps checkout closed")
assert.match(rankPromote, /Client cannot supply rank/, "rank promote rejects client rank")
assert.doesNotMatch(rankPromote, /fgubaqoftdeefcakejwu/, "rank promote never targets Aureus")

const persistRank = readFileSync(new URL("../src/lib/persistRank.server.ts", import.meta.url), "utf8")
assert.match(persistRank, /ua_user_ranks/, "rank persist upserts Ubuntu ranks")
assert.match(persistRank, /ua_rank_history/, "rank persist writes rank history")
assert.match(persistRank, /ua_rank_promotions/, "rank persist writes promotion rows")
assert.match(persistRank, /Ubuntu user is not active/, "rank persist refuses inactive members")
assert.doesNotMatch(persistRank, /fgubaqoftdeefcakejwu/, "rank persist never targets Aureus")

const schema13 = readFileSync(new URL("../supabase/ubuntu-only/0013_ua_rank_promotions.sql", import.meta.url), "utf8")
assert.match(schema13, /NEVER run this on Aureus production/, "0013 refuses Aureus")
assert.match(schema13, /ua_rank_promotions/, "0013 adds Ubuntu rank promotions")

const rankProgressRoute = readFileSync(new URL("../src/routes/api/admin/ranks/progress.ts", import.meta.url), "utf8")
assert.match(rankProgressRoute, /UA_COMMERCE_CONFIRM_SECRET/, "rank progress is secret-gated")
assert.match(rankProgressRoute, /rankProgress/, "rank progress uses the shared progress calculator")
assert.match(rankProgressRoute, /checkoutEnabled: false/, "rank progress keeps checkout closed")
assert.match(rankProgressRoute, /taken from Ubuntu ua_user_ranks/, "rank progress rejects client rank")
assert.doesNotMatch(rankProgressRoute, /persistRankPromotion/, "rank progress does not promote")
assert.doesNotMatch(rankProgressRoute, /fgubaqoftdeefcakejwu/, "rank progress never targets Aureus")

const persistRankProgress = readFileSync(new URL("../src/lib/persistRankProgress.server.ts", import.meta.url), "utf8")
assert.match(persistRankProgress, /loadRankProgressSnapshot/, "rank progress loader exists")
assert.match(persistRankProgress, /ua_team_volume/, "rank progress reads Ubuntu team volume")
assert.doesNotMatch(persistRankProgress, /\.insert\(|\.update\(|\.delete\(/, "rank progress loader is read-only")
assert.doesNotMatch(persistRankProgress, /fgubaqoftdeefcakejwu/, "rank progress loader never targets Aureus")

const financeSummary = readFileSync(new URL("../src/routes/api/admin/finance/summary.ts", import.meta.url), "utf8")
assert.match(financeSummary, /UA_COMMERCE_CONFIRM_SECRET/, "finance summary is secret-gated")
assert.match(financeSummary, /loadFinanceSummary/, "finance summary reads Ubuntu totals")
assert.match(financeSummary, /checkoutEnabled: false/, "finance summary keeps checkout closed")
assert.doesNotMatch(financeSummary, /confirmCommercePayment/, "finance summary does not confirm payment")
assert.doesNotMatch(financeSummary, /fgubaqoftdeefcakejwu/, "finance summary never targets Aureus")

const persistFinance = readFileSync(new URL("../src/lib/persistFinanceRead.server.ts", import.meta.url), "utf8")
assert.match(persistFinance, /loadFinanceSummary/, "finance loader exists")
assert.match(persistFinance, /ua_commission_transactions/, "finance loader reads Gap ledger")
assert.doesNotMatch(persistFinance, /\.insert\(|\.update\(|\.upsert\(|\.delete\(/, "finance loader is read-only")
assert.doesNotMatch(persistFinance, /fgubaqoftdeefcakejwu/, "finance loader never targets Aureus")

const financePage = readFileSync(new URL("../src/routes/admin/finance.tsx", import.meta.url), "utf8")
assert.match(financePage, /Checkout is not open|checkout is not open/, "finance page says checkout is not open")
assert.doesNotMatch(financePage, /\/api\/cards\/order/, "finance page cannot create card orders")
assert.doesNotMatch(financePage, /\/api\/fractions\/order/, "finance page cannot create fraction orders")
assert.doesNotMatch(financePage, /\/api\/admin\/commerce\/confirm-payment/, "finance page cannot confirm payment")

const schema14 = readFileSync(new URL("../supabase/ubuntu-only/0014_ua_marketplace_companies.sql", import.meta.url), "utf8")
assert.match(schema14, /NEVER run this on Aureus production/, "0014 refuses Aureus")
assert.match(schema14, /ua_marketplace_companies/, "0014 adds Ubuntu marketplace companies")

const schema15 = readFileSync(new URL("../supabase/ubuntu-only/0015_ua_marketplace_orders.sql", import.meta.url), "utf8")
assert.match(schema15, /NEVER run this on Aureus production/, "0015 refuses Aureus")
assert.match(schema15, /ua_marketplace_orders/, "0015 adds Ubuntu marketplace orders")
assert.match(schema15, /ua_company_settlements/, "0015 adds Ubuntu company settlements")

const adminCompanies = readFileSync(new URL("../src/routes/api/admin/marketplace/companies.ts", import.meta.url), "utf8")
assert.match(adminCompanies, /UA_COMMERCE_CONFIRM_SECRET/, "admin marketplace companies are secret-gated")
assert.match(adminCompanies, /checkoutEnabled: false/, "admin marketplace companies keep checkout closed")
assert.doesNotMatch(adminCompanies, /fgubaqoftdeefcakejwu/, "admin marketplace companies never target Aureus")

const adminProducts = readFileSync(new URL("../src/routes/api/admin/marketplace/products.ts", import.meta.url), "utf8")
assert.match(adminProducts, /UA_COMMERCE_CONFIRM_SECRET/, "admin marketplace products are secret-gated")
assert.match(adminProducts, /STANDARD_25/, "admin marketplace products force shared Gap")
assert.match(adminProducts, /checkoutEnabled: false/, "admin marketplace products keep checkout closed")

const adminSettle = readFileSync(new URL("../src/routes/api/admin/marketplace/settle.ts", import.meta.url), "utf8")
assert.match(adminSettle, /UA_COMMERCE_CONFIRM_SECRET/, "admin marketplace settle is secret-gated")
assert.match(adminSettle, /settleMarketplaceOrder/, "admin marketplace settle uses shared Gap settlement")
assert.match(adminSettle, /Client-supplied rank chains are rejected/, "admin marketplace settle rejects client members")
assert.match(adminSettle, /checkoutEnabled: false/, "admin marketplace settle keeps checkout closed")
assert.doesNotMatch(adminSettle, /fgubaqoftdeefcakejwu/, "admin marketplace settle never targets Aureus")

const publicMarketOrder = readFileSync(new URL("../src/routes/api/marketplace/order.ts", import.meta.url), "utf8")
assert.match(publicMarketOrder, /Public checkout is not open/, "public marketplace order stays closed")
assert.match(publicMarketOrder, /status: 403/, "public marketplace order stays 403")
assert.doesNotMatch(publicMarketOrder, /fgubaqoftdeefcakejwu/, "public marketplace order never targets Aureus")

const marketSettle = readFileSync(new URL("../src/lib/marketplaceSettlement.mjs", import.meta.url), "utf8")
assert.match(marketSettle, /processGapCover/, "marketplace settlement uses shared Gap Cover")
assert.match(marketSettle, /STANDARD_25/, "marketplace settlement is STANDARD_25 only")
assert.doesNotMatch(marketSettle, /CUSTOM_30/, "marketplace settlement has no second plan")

console.log("ubuntu-afrique-db-isolation.test.mjs: OK")
