/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateIndexRouteImport } from './routes/affiliate/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardInvestRouteImport } from './routes/dashboard/invest'
import { Route as DashboardCardsRouteImport } from './routes/dashboard/cards'
import { Route as DashboardNftRouteImport } from './routes/dashboard/nft'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceDashboardRouteImport } from './routes/marketplace/dashboard'
import { Route as MarketplaceCompanySlugRouteImport } from './routes/marketplace/company/$slug'
import { Route as NftIndexRouteImport } from './routes/nft/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateIndexRoute = AffiliateIndexRouteImport.update({
  id: '/affiliate/',
  path: '/affiliate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestRoute = DashboardInvestRouteImport.update({
  id: '/dashboard/invest',
  path: '/dashboard/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCardsRoute = DashboardCardsRouteImport.update({
  id: '/dashboard/cards',
  path: '/dashboard/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNftRoute = DashboardNftRouteImport.update({
  id: '/dashboard/nft',
  path: '/dashboard/nft',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceDashboardRoute = MarketplaceDashboardRouteImport.update({
  id: '/marketplace/dashboard',
  path: '/marketplace/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCompanySlugRoute = MarketplaceCompanySlugRouteImport.update({
  id: '/marketplace/company/$slug',
  path: '/marketplace/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NftIndexRoute = NftIndexRouteImport.update({
  id: '/nft/',
  path: '/nft/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/nft': typeof DashboardNftRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/dashboard': typeof MarketplaceDashboardRoute
  '/marketplace/company/$slug': typeof MarketplaceCompanySlugRoute
  '/nft/': typeof NftIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/nft': typeof DashboardNftRoute
  '/affiliate': typeof AffiliateIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/marketplace/dashboard': typeof MarketplaceDashboardRoute
  '/marketplace/company/$slug': typeof MarketplaceCompanySlugRoute
  '/nft': typeof NftIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/nft': typeof DashboardNftRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/dashboard': typeof MarketplaceDashboardRoute
  '/marketplace/company/$slug': typeof MarketplaceCompanySlugRoute
  '/nft/': typeof NftIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/invest'
    | '/dashboard/cards'
    | '/dashboard/nft'
    | '/affiliate/'
    | '/dashboard/'
    | '/marketplace/'
    | '/marketplace/dashboard'
    | '/marketplace/company/$slug'
    | '/nft/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/invest'
    | '/dashboard/cards'
    | '/dashboard/nft'
    | '/affiliate'
    | '/dashboard'
    | '/marketplace'
    | '/marketplace/dashboard'
    | '/marketplace/company/$slug'
    | '/nft'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/invest'
    | '/dashboard/cards'
    | '/dashboard/nft'
    | '/affiliate/'
    | '/dashboard/'
    | '/marketplace/'
    | '/marketplace/dashboard'
    | '/marketplace/company/$slug'
    | '/nft/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardInvestRoute: typeof DashboardInvestRoute
  DashboardCardsRoute: typeof DashboardCardsRoute
  DashboardNftRoute: typeof DashboardNftRoute
  AffiliateIndexRoute: typeof AffiliateIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceDashboardRoute: typeof MarketplaceDashboardRoute
  MarketplaceCompanySlugRoute: typeof MarketplaceCompanySlugRoute
  NftIndexRoute: typeof NftIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/': {
      id: '/affiliate/'
      path: '/affiliate'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AffiliateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invest': {
      id: '/dashboard/invest'
      path: '/dashboard/invest'
      fullPath: '/dashboard/invest'
      preLoaderRoute: typeof DashboardInvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cards': {
      id: '/dashboard/cards'
      path: '/dashboard/cards'
      fullPath: '/dashboard/cards'
      preLoaderRoute: typeof DashboardCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/nft': {
      id: '/dashboard/nft'
      path: '/dashboard/nft'
      fullPath: '/dashboard/nft'
      preLoaderRoute: typeof DashboardNftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/dashboard': {
      id: '/marketplace/dashboard'
      path: '/marketplace/dashboard'
      fullPath: '/marketplace/dashboard'
      preLoaderRoute: typeof MarketplaceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/company/$slug': {
      id: '/marketplace/company/$slug'
      path: '/marketplace/company/$slug'
      fullPath: '/marketplace/company/$slug'
      preLoaderRoute: typeof MarketplaceCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft/': {
      id: '/nft/'
      path: '/nft'
      fullPath: '/nft/'
      preLoaderRoute: typeof NftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardInvestRoute: DashboardInvestRoute,
  DashboardCardsRoute: DashboardCardsRoute,
  DashboardNftRoute: DashboardNftRoute,
  AffiliateIndexRoute: AffiliateIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceDashboardRoute: MarketplaceDashboardRoute,
  MarketplaceCompanySlugRoute: MarketplaceCompanySlugRoute,
  NftIndexRoute: NftIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
